// Packet → decoder-key hint maps. Used by the Conv Decoders orchestrator to
// prefer the packet's known application protocol / port before falling back
// to byte-heuristic detection in autoDetectProtoFromBytes.

// Application-protocol names (as they appear in packet info) → decoder key.
const PROTOCOL_DECODER_HINTS = new Map([
    ["http", "http"],
    ["http2", "http"],
    ["https", "http"],
    ["ssh", "ssh"],
    ["telnet", "telnet"],
    ["smtp", "smtp"],
    ["ftp", "ftp"],
    ["pop3", "pop3"],
    ["imap", "imap"],
    ["ldap", "ldap"],
    ["smb", "smb"],
    ["epmap", "epmap"],
    ["ssdp", "ssdp"],
    ["upnp", "ssdp"],
    ["grpc", "grpc"],
    ["g-rpc", "grpc"],
    ["sip", "sip"],
    ["smpp", "smpp"],
    ["soulseek", "soulseek"],
    ["bittorrent", "bittorrent"],
    ["kerberos", "kerberos"],
    ["krb5", "kerberos"],
    ["krb5sec", "kerberos"],
    ["dns", "dns"],
    ["mdns", "mdns"],
    ["bonjour", "mdns"],
    ["dnssd", "mdns"],
    ["llmnr", "llmnr"],
    ["nbns", "nbns"],
    ["netbios-ns", "nbns"],
    ["netbios-name-service", "nbns"],
    ["nbdgm", "nbdgm"],
    ["netbios-dgm", "nbdgm"],
    ["netbios-datagram", "nbdgm"],
    ["netbios-datagram-service", "nbdgm"],
    ["snmp", "snmp"],
    ["dhcp", "dhcp"],
    ["dhcpv6", "dhcpv6"],
    ["iso8583", "iso8583"],
    ["iso-8583", "iso8583"],
    ["modbus", "modbus"],
    ["modbus-tcp", "modbus"],
    ["dnp3", "dnp3"],
    ["dnp-3", "dnp3"],
    ["s7comm", "s7comm"],
    ["s7-comm", "s7comm"],
    ["s7", "s7comm"],
    ["ospf", "ospf"],
    ["hsrp", "hsrp"],
    ["lacp", "lacp"],
    ["cdp", "cdp"],
    ["mndp", "mndp"],
    ["mikrotik-neighbor-discovery", "mndp"],
    ["mikrotik", "mndp"],
    ["websocket", "websocket"],
    ["web-socket", "websocket"],
    ["ws", "websocket"],
    ["jpeg", "jpeg"],
    ["png", "png"],
    ["gif", "gif"],
    ["webp", "webp"],
    ["imagejpeg", "jpeg"],
    ["imagepng", "png"],
    ["imagegif", "gif"],
    ["imagewebp", "webp"],
    ["plaintext", "plaintext"],
]);

// Well-known transport ports → decoder key.
const PORT_DECODER_HINTS = new Map([
    [21, "ftp"],
    [22, "ssh"],
    [23, "telnet"],
    [25, "smtp"],
    [80, "http"],
    [110, "pop3"],
    [143, "imap"],
    [389, "ldap"],
    [443, "http"],
    [445, "smb"],
    [135, "epmap"],
    [1900, "ssdp"],
    [50051, "grpc"],
    [587, "smtp"],
    [8080, "http"],
    [5060, "sip"],
    [5061, "sip"],
    [2775, "smpp"],
    [88, "kerberos"],
    [750, "kerberos"],
    [464, "kerberos"],
    [53, "dns"],
    [5353, "mdns"],
    [5355, "llmnr"],
    [137, "nbns"],
    [138, "nbdgm"],
    [161, "snmp"],
    [162, "snmp"],
    [67, "dhcp"],
    [68, "dhcp"],
    [546, "dhcpv6"],
    [547, "dhcpv6"],
    [8583, "iso8583"],
    [5000, "iso8583"],
    [5001, "iso8583"],
    [14401, "iso8583"],
    [502, "modbus"],
    [20000, "dnp3"],
    [102, "s7comm"],
    [89, "ospf"],
    [1985, "hsrp"],
    [5678, "mndp"],
    [2234, "soulseek"],
    [2242, "soulseek"],
    [6881, "bittorrent"],
    [6882, "bittorrent"],
    [6883, "bittorrent"],
    [6884, "bittorrent"],
    [6885, "bittorrent"],
    [6886, "bittorrent"],
    [6887, "bittorrent"],
    [6888, "bittorrent"],
    [6889, "bittorrent"],
]);

module.exports = { PROTOCOL_DECODER_HINTS, PORT_DECODER_HINTS };
