"""Build the ``snitch`` (or ``snitch-extract``) onefile binary via
PyInstaller, with DT_RUNPATH rewriting for ``.so`` files we cannot
edit in place.

Why this exists
---------------
``scripts/build-backend.js`` and ``build-extractor.js`` previously
invoked ``python3 -m PyInstaller snitch.py``. PyInstaller reads
``.so`` files straight from the active site-packages and bundles them.
If a wheel ships ``.so`` files whose ``DT_RUNPATH`` is ``$ORIGIN``-
relative (``libabsl_*.so.20260526`` from grpcio / tensorboard /
pyarrow) and the build environment has those wheels installed
**system-wide** (root-owned, not writable), PyInstaller copies the
un-patched ``.so`` into the onefile archive and ``staticx`` then
refuses to re-wrap with::

    staticx: Unsupported PyInstaller input
      /tmp/staticx-pyi-XXX/libabsl_*.so.20260526: DT_RUNPATH='$ORIGIN'

``scripts/stage_patched_sos.py`` runs first and emits
``${BUILD_WORK_DIR}/patched-sos/manifest.json``. This script generates
a PyInstaller ``.spec`` file that:

1. Runs ``Analysis`` on the entry script (with ``--collect-binaries`` /
   ``--collect-data`` flags applied).
2. After ``Analysis``, walks ``a.binaries`` and substitutes
   ``src_name`` with the cached, pre-patched copy for any entry whose
   original path is in the manifest.
3. Runs ``PYZ`` and ``EXE`` to build the onefile binary.

The manifest schema::

    {
        "version": 1,
        "cache_dir": "/abs/path/to/build/pyinstaller/patched-sos",
        "python": "/abs/path/to/python",
        "patches": {
            "/abs/path/to/original/.../libabsl_base.so.20260526":
                "/abs/path/to/build/.../libabsl_base.so.20260526"
        }
    }

The generated ``.spec`` file is dropped next to ``workpath`` and then
PyInstaller's CLI is invoked with that ``.spec`` as the only positional
argument so it skips spec generation and just runs our patched spec.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path


_SPEC_TEMPLATE = """\
# Auto-generated by scripts/run_pyinstaller.py -- DO NOT EDIT BY HAND.
# Re-running the build regenerates this file.

import json
import os
from pathlib import Path

# Load the patched-.so manifest so the Analysis step can re-route
# ``a.binaries[].src_name`` entries to the cached, DT_RUNPATH-free
# copies.
_MANIFEST_PATH = {_manifest_path!r}
_PATCHES = {{}}
_CACHE_DIR = None
if _MANIFEST_PATH and os.path.isfile(_MANIFEST_PATH):
    with open(_MANIFEST_PATH, "r", encoding="utf-8") as _f:
        _MANIFEST = json.load(_f)
    _PATCHES = _MANIFEST.get("patches", {{}}) or {{}}
    _CACHE_DIR = _MANIFEST.get("cache_dir")


a = Analysis(
    {_entry_script},
    pathex={_pathex!r},
    binaries=[],
    datas=[],
    hiddenimports={_hiddenimports!r},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes={_excludes!r},
    noarchive={_noarchive},
    optimize=0,
)

# Apply ``--collect-binaries`` / ``--collect-data`` flags. These are
# spec-time helpers; ``Analysis`` exposes them as ``collect_binaries``
# and ``collect_data`` methods in PyInstaller 6.x.
for _pkg in {_collect_binaries!r}:
    if hasattr(a, "collect_binaries"):
        a.collect_binaries(_pkg)
for _pkg in {_collect_data!r}:
    if hasattr(a, "collect_data"):
        a.collect_data(_pkg)


# Substitute ``a.binaries[].src_name`` for any cached .so files. The
# cache is populated by ``stage_patched_sos.py`` with patchelf-rewritten
# copies of root-owned DT_RUNPATH files. Without this, staticx would
# later fail with ``Unsupported DT_RUNPATH '$ORIGIN'`` on libabsl /
# gRPC / tensorboard binaries.
if _PATCHES:
    _new_binaries = []
    _substituted = 0
    for _entry in a.binaries:
        _dest_name, _src_name, _typecode = _entry[:3]
        if _src_name in _PATCHES:
            _new_binaries.append((_dest_name, _PATCHES[_src_name], _typecode))
            _substituted += 1
        else:
            _new_binaries.append(_entry)
    a.binaries = _new_binaries
    print(
        f"[run-pyinstaller-spec] substituted {{_substituted}} .so "
        f"src_name(s) with cached, patched copies from {{_CACHE_DIR}}"
    )


pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={_name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx={_upx},
    upx_exclude=[],
    runtime_tmpdir=None,
    console={_console},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"""


def _render_spec(args: argparse.Namespace) -> str:
    pathex: list[str] = []
    for entry in args.pathex:
        pathex.extend(entry.split(os.pathsep))
    # PyInstaller's ``Analysis`` expects ``scripts`` as a list of
    # Path-like strings. We embed the list as a Python literal so
    # the spec file can be exec()'d as-is.
    scripts_repr = "[" + repr(str(args.entry_script.resolve())) + "]"
    return _SPEC_TEMPLATE.format(
        _manifest_path=str(args.manifest.resolve()) if args.manifest else "",
        _entry_script=scripts_repr,
        _pathex=pathex,
        _hiddenimports=args.hidden_import,
        _excludes=args.exclude_module,
        _noarchive=args.noarchive,
        _collect_binaries=args.collect_binaries,
        _collect_data=args.collect_data,
        _name=args.name,
        _upx=args.upx,
        _console=args.console,
    )


def _parse_cli(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n\n", 1)[0],
        allow_abbrev=False,
    )
    parser.add_argument("entry_script", type=Path)
    parser.add_argument("--name", required=True)
    parser.add_argument("--distpath", type=Path, required=True)
    parser.add_argument("--workpath", type=Path, required=True)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="JSON manifest produced by stage_patched_sos.py",
    )
    parser.add_argument(
        "--collect-binaries",
        action="append",
        default=[],
        help=(
            "PyInstaller ``collect_binaries`` target. May be repeated. "
            "(e.g. --collect-binaries scipy --collect-binaries numpy)"
        ),
    )
    parser.add_argument(
        "--collect-data",
        action="append",
        default=[],
        help=(
            "PyInstaller ``collect_data`` target. May be repeated. "
            "(e.g. --collect-data scipy)"
        ),
    )
    parser.add_argument(
        "--hidden-import",
        action="append",
        default=[],
        help="PyInstaller hiddenimports. May be repeated.",
    )
    parser.add_argument(
        "--exclude-module",
        action="append",
        default=[],
        help="PyInstaller excludes. May be repeated.",
    )
    parser.add_argument(
        "--console",
        action="store_true",
        default=True,
        help="Build a console executable (the default for snitch).",
    )
    parser.add_argument(
        "--no-console",
        dest="console",
        action="store_false",
        help="Build a windowed executable (macOS .app bundle).",
    )
    parser.add_argument(
        "--upx",
        action="store_true",
        default=False,
        help="Run UPX on the bundled binaries (snitch uses this).",
    )
    parser.add_argument(
        "--noarchive",
        action="store_true",
        default=False,
        help="Pass ``noarchive=True`` to Analysis (default false).",
    )
    parser.add_argument(
        "--pathex",
        action="append",
        default=[],
        help="Extra ``pathex`` entry for PyInstaller. May be repeated.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_cli(argv if argv is not None else sys.argv[1:])

    # Ensure distpath / workpath exist (PyInstaller expects this).
    args.distpath.mkdir(parents=True, exist_ok=True)
    args.workpath.mkdir(parents=True, exist_ok=True)

    # 1. Render and write the patched spec file.
    spec_text = _render_spec(args)
    spec_path = args.workpath / f"{args.name}.pyinstaller.spec"
    spec_path.write_text(spec_text, encoding="utf-8")
    print(f"[run-pyinstaller] wrote patched spec at {spec_path}")

    # 2. Invoke PyInstaller's CLI with our spec file as the only
    # positional argument so it skips spec generation. The ``--`` is
    # the conventional separator between PyInstaller flags and any
    # user-provided flags; we don't have user flags, so we omit it.
    # Use ``--flag=value`` form to avoid argparse ambiguity when the
    # flag's metavar looks like another positional argument.
    pyi_args = [
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        f"--distpath={args.distpath.resolve()}",
        f"--workpath={args.workpath.resolve()}",
        str(spec_path.resolve()),
    ]
    print(
        "[run-pyinstaller] running: "
        f"{shlex.join([sys.executable, *pyi_args])}"
    )
    result = subprocess.run([sys.executable, *pyi_args])
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())