"""Build the ``snitch`` (or ``snitch-extract``) onefile binary via
PyInstaller, with DT_RUNPATH rewriting for ``.so`` files we cannot
edit in place.

Why this exists
---------------
``scripts/build-backend.js`` and ``build-extractor.js`` previously
invoked ``python3 -m PyInstaller snitch.py``. PyInstaller reads
``.so`` files straight from the active site-packages and bundles them.
If a wheel ships ``.so`` files whose ``DT_RUNPATH`` is ``$ORIGIN``-
relative (``libabsl_*.so.20260526`` from grpcio / tensorboard /
pyarrow) and the build environment has those wheels installed
**system-wide** (root-owned, not writable), PyInstaller copies the
un-patched ``.so`` into the onefile archive and ``staticx`` then
refuses to re-wrap with::

    staticx: Unsupported PyInstaller input
      /tmp/staticx-pyi-XXX/libabsl_*.so.20260526: DT_RUNPATH='$ORIGIN'

``scripts/stage_patched_sos.py`` runs first and emits
``${BUILD_WORK_DIR}/patched-sos/manifest.json``. This script generates
a PyInstaller ``.spec`` file that:

1. Runs ``Analysis`` on the entry script (with ``--collect-binaries`` /
   ``--collect-data`` flags applied).
2. After ``Analysis``, walks ``a.binaries`` and substitutes
   ``src_name`` with the cached, pre-patched copy for any entry whose
   original path is in the manifest.
3. Runs ``PYZ`` and ``EXE`` to build the onefile binary.

The manifest schema::

    {
        "version": 1,
        "cache_dir": "/abs/path/to/build/pyinstaller/patched-sos",
        "python": "/abs/path/to/python",
        "patches": {
            "/abs/path/to/original/.../libabsl_base.so.20260526":
                "/abs/path/to/build/.../libabsl_base.so.20260526"
        }
    }

The generated ``.spec`` file is dropped next to ``workpath`` and then
PyInstaller's CLI is invoked with that ``.spec`` as the only positional
argument so it skips spec generation and just runs our patched spec.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import site
import subprocess
import sys
import sysconfig
from pathlib import Path


_SPEC_TEMPLATE = """\
# Auto-generated by scripts/run_pyinstaller.py -- DO NOT EDIT BY HAND.
# Re-running the build regenerates this file.

import json
import os
import shutil
import subprocess
from pathlib import Path

# Load the pre-staged.patchelf cache (populated by
# stage_patched_sos.py). Keys are absolute paths to the original
# (un-patched) .so files; values are writable cached copies with
# DT_RUNPATH rewritten to DT_RPATH.
_MANIFEST_PATH = {_manifest_path!r}
_PATCHES = {{}}
_CACHE_DIR = None
if _MANIFEST_PATH and os.path.isfile(_MANIFEST_PATH):
    with open(_MANIFEST_PATH, "r", encoding="utf-8") as _f:
        _MANIFEST = json.load(_f)
    _PATCHES = _MANIFEST.get("patches", {{}}) or {{}}
    _CACHE_DIR = _MANIFEST.get("cache_dir")


a = Analysis(
    {_entry_script},
    pathex={_pathex!r},
    binaries=[],
    datas=[],
    hiddenimports={_hiddenimports!r},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes={_excludes!r},
    noarchive={_noarchive},
    optimize=0,
)

# Apply ``--collect-binaries`` / ``--collect-data`` flags. These are
# spec-time helpers; ``Analysis`` exposes them as ``collect_binaries``
# and ``collect_data`` methods in PyInstaller 6.x.
for _pkg in {_collect_binaries!r}:
    if hasattr(a, "collect_binaries"):
        a.collect_binaries(_pkg)
for _pkg in {_collect_data!r}:
    if hasattr(a, "collect_data"):
        a.collect_data(_pkg)


def _read_dynamic_section(path):
    '''Return list of (tag, value) pairs from the dynamic section of
    the given ELF file. Uses ``patchelf --print-rpath`` for the
    rpath/runpath tags we care about, falling back to ``readelf -d`` if
    patchelf is not available.'''
    import re
    try:
        out = subprocess.run(
            ["patchelf", "--print-rpath", path],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        out = ""
    runpath = out
    try:
        out = subprocess.run(
            ["patchelf", "--print-needed", path],
            capture_output=True, text=True, check=True,
        ).stdout.splitlines()
    except (FileNotFoundError, subprocess.CalledProcessError):
        out = []
    return runpath, out


def _ensure_patched(src_name, dest_name):
    '''Return a path to a DT_RUNPATH-free copy of ``src_name``.

    Order of operations:
      1. If ``src_name`` is already in the manifest cache, use the
         cached copy directly.
      2. Otherwise, try to patchelf ``src_name`` in place. If it
         works, return ``src_name`` unchanged.
      3. Otherwise (root-owned, not writable), copy to a writable
         subdirectory of the cache and patchelf the copy. The copy
         is keyed by the relative path of the source so subsequent
         builds reuse it.
    '''
    if src_name in _PATCHES:
        return _PATCHES[src_name]
    if not os.path.isfile(src_name):
        return src_name
    runpath, _ = _read_dynamic_section(src_name)
    if not runpath:
        return src_name
    # Already a DT_RPATH, not a DT_RUNPATH. Try in place first.
    try:
        subprocess.run(
            ["patchelf", "--remove-rpath", src_name],
            capture_output=True, check=True,
        )
        return src_name
    except (subprocess.CalledProcessError, FileNotFoundError, PermissionError, OSError):
        pass
    # In-place patchelf failed (probably root-owned). Stage to the
    # cache directory and patchelf there.
    if not _CACHE_DIR:
        _CACHE_DIR_RUNTIME = os.path.join(
            os.path.dirname(__file__) or os.getcwd(),
            "build",
            "pyinstaller",
            "patched-sos",
        )
    else:
        _CACHE_DIR_RUNTIME = _CACHE_DIR
    # Key the cached copy by the absolute path of the source so we
    # reuse the same file across builds.
    ab = os.path.abspath(src_name)
    cache_path = os.path.join(_CACHE_DIR_RUNTIME, ab.lstrip("/"))
    cache_path = cache_path.replace(os.sep + ".", os.sep + "_dot_")
    os.makedirs(os.path.dirname(cache_path), exist_ok=True)
    if not os.path.isfile(cache_path):
        shutil.copy2(ab, cache_path)
        os.chmod(cache_path, 0o644)
    try:
        subprocess.run(
            ["patchelf", "--remove-rpath", cache_path],
            capture_output=True, check=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        # If patchelf still fails after staging, give up and return
        # the original -- the build will fail downstream with a
        # clearer error than ours.
        return src_name
    return cache_path


# Substitute ``a.binaries[].src_name`` for any cached .so files. The
# cache is populated by ``stage_patched_sos.py`` with patchelf-rewritten
# copies of root-owned DT_RUNPATH files. Without this, staticx would
# later fail with ``Unsupported DT_RUNPATH '$ORIGIN'`` on libabsl /
# gRPC / tensorboard binaries.
_new_binaries = []
_substituted = 0
for _entry in a.binaries:
    _dest_name, _src_name, _typecode = _entry[:3]
    if _src_name in _PATCHES:
        _new_binaries.append((_dest_name, _PATCHES[_src_name], _typecode))
        _substituted += 1
        continue
    # Fast-path: if the .so ends with .so and lives somewhere we
    # couldn't patchelf in place (i.e. it still has DT_RUNPATH),
    # route through the cache on demand.
    if _src_name.endswith(".so") or ".so." in os.path.basename(_src_name):
        _new_src = _ensure_patched(_src_name, _dest_name)
        if _new_src != _src_name:
            _new_binaries.append((_dest_name, _new_src, _typecode))
            _substituted += 1
            continue
    _new_binaries.append(_entry)
a.binaries = _new_binaries
print(
    f"[run-pyinstaller-spec] substituted {{_substituted}} .so "
    f"src_name(s) with cached, patched copies from {{_CACHE_DIR or '<build-time cache>'}}"
)


pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={_name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx={_upx},
    upx_exclude=[],
    runtime_tmpdir=None,
    console={_console},
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon={_icon!r},
)
"""


def _render_spec(args: argparse.Namespace) -> str:
    pathex: list[str] = []
    for entry in args.pathex:
        pathex.extend(entry.split(os.pathsep))
    # PyInstaller's ``Analysis`` expects ``scripts`` as a list of
    # Path-like strings. We embed the list as a Python literal so
    # the spec file can be exec()'d as-is.
    scripts_repr = "[" + repr(str(args.entry_script.resolve())) + "]"
    return _SPEC_TEMPLATE.format(
        _manifest_path=str(args.manifest.resolve()) if args.manifest else "",
        _entry_script=scripts_repr,
        _pathex=pathex,
        _hiddenimports=args.hidden_import,
        _excludes=args.exclude_module,
        _noarchive=args.noarchive,
        _collect_binaries=args.collect_binaries,
        _collect_data=args.collect_data,
        _name=args.name,
        _upx=args.upx,
        _console=args.console,
        _icon=str(args.icon.resolve()) if args.icon else None,
    )


def _parse_cli(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n\n", 1)[0],
        allow_abbrev=False,
    )
    parser.add_argument("entry_script", type=Path)
    parser.add_argument("--name", required=True)
    parser.add_argument("--distpath", type=Path, required=True)
    parser.add_argument("--workpath", type=Path, required=True)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=None,
        help="JSON manifest produced by stage_patched_sos.py",
    )
    parser.add_argument(
        "--collect-binaries",
        action="append",
        default=[],
        help=(
            "PyInstaller ``collect_binaries`` target. May be repeated. "
            "(e.g. --collect-binaries scipy --collect-binaries numpy)"
        ),
    )
    parser.add_argument(
        "--collect-data",
        action="append",
        default=[],
        help=(
            "PyInstaller ``collect_data`` target. May be repeated. "
            "(e.g. --collect-data scipy)"
        ),
    )
    parser.add_argument(
        "--hidden-import",
        action="append",
        default=[],
        help="PyInstaller hiddenimports. May be repeated.",
    )
    parser.add_argument(
        "--exclude-module",
        action="append",
        default=[],
        help="PyInstaller excludes. May be repeated.",
    )
    parser.add_argument(
        "--console",
        action="store_true",
        default=True,
        help="Build a console executable (the default for snitch).",
    )
    parser.add_argument(
        "--no-console",
        dest="console",
        action="store_false",
        help="Build a windowed executable (macOS .app bundle).",
    )
    parser.add_argument(
        "--upx",
        action="store_true",
        default=False,
        help="Run UPX on the bundled binaries (snitch uses this).",
    )
    parser.add_argument(
        "--noarchive",
        action="store_true",
        default=False,
        help="Pass ``noarchive=True`` to Analysis (default false).",
    )
    parser.add_argument(
        "--pathex",
        action="append",
        default=[],
        help="Extra ``pathex`` entry for PyInstaller. May be repeated.",
    )
    parser.add_argument(
        "--icon",
        type=Path,
        default=None,
        help=(
            "Path to an icon file (.ico on Windows, .icns on macOS) to "
            "embed in the resulting binary. Omit on Linux -- the "
            "PyInstaller onefile is console-only and has no icon."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_cli(argv if argv is not None else sys.argv[1:])

    # Ensure distpath / workpath exist (PyInstaller expects this).
    args.distpath.mkdir(parents=True, exist_ok=True)
    args.workpath.mkdir(parents=True, exist_ok=True)

    # 1. Render and write the patched spec file.
    spec_text = _render_spec(args)
    spec_path = args.workpath / f"{args.name}.pyinstaller.spec"
    spec_path.write_text(spec_text, encoding="utf-8")
    print(f"[run-pyinstaller] wrote patched spec at {spec_path}")

    # 2. Compute ``LD_LIBRARY_PATH`` additions so PyInstaller's
    # isolated subprocess (used by hooks like ``hook-matplotlib.py``)
    # can find vendored shared libraries that numpy / scipy wheels
    # ship under ``<pkg>.libs/`` directories. These libraries live
    # next to the package but are NOT on the loader's default search
    # path, so importing numpy (via matplotlib -> numpy) in a
    # subprocess fails with ``libscipy_openblas64_-XXX.so: cannot
    # open shared object file`` and aborts the build.
    # See https://github.com/pypa/manylinux for the ``.libs``
    # convention.
    env = os.environ.copy()
    libs_dirs = _find_libs_dirs()
    if libs_dirs:
        existing = env.get("LD_LIBRARY_PATH", "")
        env["LD_LIBRARY_PATH"] = os.pathsep.join(
            libs_dirs + ([existing] if existing else [])
        )
        print(
            "[run-pyinstaller] LD_LIBRARY_PATH additions: "
            f"{libs_dirs}"
        )

    # 3. Invoke PyInstaller's CLI with our spec file as the only
    # positional argument so it skips spec generation. The ``--`` is
    # the conventional separator between PyInstaller flags and any
    # user-provided flags; we don't have user flags, so we omit it.
    # Use ``--flag=value`` form to avoid argparse ambiguity when the
    # flag's metavar looks like another positional argument.
    pyi_args = [
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        f"--distpath={args.distpath.resolve()}",
        f"--workpath={args.workpath.resolve()}",
        str(spec_path.resolve()),
    ]
    print(
        "[run-pyinstaller] running: "
        f"{shlex.join([sys.executable, *pyi_args])}"
    )
    result = subprocess.run([sys.executable, *pyi_args], env=env)
    return result.returncode


def _find_libs_dirs() -> list[str]:
    """Return a list of directories containing vendored ``.so`` files
    that should be on ``LD_LIBRARY_PATH`` for the build's Python
    subprocess to succeed.

    Manylinux wheels (numpy, scipy, gRPC, etc.) ship their native
    libraries in ``<package>.libs/`` directories next to the package
    itself. When the Python interpreter imports the package, the
    CPython ABI extension module is loaded from the package dir, but
    the *vendored* libraries it depends on (e.g.
    ``libscipy_openblas64_*.so``, ``libgfortran-*.so.5``) are loaded
    via the dynamic linker, which only checks standard paths and
    ``LD_LIBRARY_PATH`` -- not the package's own directory.

    We walk every site-packages directory Python knows about and
    collect any ``<something>.libs`` directory we find. We also walk
    the stdlib ``sysconfig`` paths so that ``/usr/lib/python3.13``-
    style distributions are covered.
    """
    candidates: list[str] = []
    roots: list[str] = []
    try:
        roots.extend(site.getsitepackages())
    except Exception:
        pass
    try:
        user = site.getusersitepackages()
        if user:
            roots.append(user)
    except Exception:
        pass
    try:
        sp = sysconfig.get_paths().get("purelib")
        if sp:
            roots.append(sp)
    except Exception:
        pass
    try:
        sp = sysconfig.get_paths().get("platlib")
        if sp:
            roots.append(sp)
    except Exception:
        pass
    for root in roots:
        try:
            for entry in os.listdir(root):
                if not entry.endswith(".libs"):
                    continue
                full = os.path.join(root, entry)
                if os.path.isdir(full):
                    candidates.append(full)
        except (FileNotFoundError, PermissionError, OSError):
            continue
    # Deduplicate while preserving order.
    seen: set[str] = set()
    unique: list[str] = []
    for c in candidates:
        if c not in seen:
            seen.add(c)
            unique.append(c)
    return unique


if __name__ == "__main__":
    raise SystemExit(main())